defaults:
  - model: lcnn
  - writer: wandb
  - metrics: example
  - datasets: asvspoof_datasets
  - dataloader: example
  - transforms: asvspoof_transforms
  - _self_

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001  # Выше, как в статьях
  weight_decay: 0.0001

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.5   # Как в STC paper
  step_size: 10  # Каждые 10 эпох

loss_function:
  _target_: src.loss.ExampleLoss

trainer:
  log_step: 50
  n_epochs: 50  # Больше эпох
  epoch_len: null
  device_tensors: ["data_object", "labels"]
  resume_from: null
  device: auto
  override: False
  monitor: "min val_EER"
  save_period: 5
  early_stop: 15
  save_dir: "saved"
  seed: 42
  max_grad_norm: 1.0

writer:
  project_name: "asvspoof2019_voice_antispoofing"
  run_name: "lcnn_asoftmax_improved"
  loss_names: ["loss"]
