defaults:
  - model: baseline
  - writer: wandb
  - metrics: example
  - datasets: asvspoof_datasets
  - dataloader: example
  - transforms: asvspoof_transforms
  - _self_

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001
  weight_decay: 0.0001

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.9
  step_size: 1

loss_function:
  _target_: src.loss.ExampleLoss

trainer:
  log_step: 50
  n_epochs: 20
  epoch_len: null
  device_tensors: ["data_object", "labels"]
  resume_from: null
  device: auto
  override: False
  monitor: "min val_EER"
  save_period: 5
  early_stop: 8
  save_dir: "saved"
  seed: 42
  max_grad_norm: 1.0

writer:
  project_name: "asvspoof2019_antispoofing"
  run_name: "lcnn_baseline"
  loss_names: ["loss"]
